<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Printable Ticket Version</title>
    <style>
        body { margin: 0; padding: 1.5rem; background: #f4f4f4; color: #2b2b2b;
               font: 15px/1.5 -apple-system, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; }
        .sheet { max-width: 1500px; margin: 0 auto; padding: 1.75rem 2rem; background: #fff;
                 border: 1px solid #e0e0e0; border-radius: 4px; }
        h1 { margin: 0 0 1.25rem; font-size: 1.35rem; font-weight: 400; color: #337ab7; }
        .meta p { margin: 0 0 0.3rem; }
        .meta em { font-style: italic; color: #2b2b2b; }
        .meta .v { font-style: normal; }
        hr { margin: 1.5rem 0; border: 0; border-top: 1px solid #e0e0e0; }
        .msg-head { margin: 0 0 0.75rem; font-weight: 700; }
        .badge { display: inline-block; margin-left: 0.35rem; padding: 0.05rem 0.4rem; border-radius: 3px;
                 background: #5bc0de; color: #fff; font-size: 0.7rem; font-weight: 700;
                 letter-spacing: 0.04em; text-transform: uppercase; vertical-align: middle; }
        .when { float: right; font-weight: 400; color: #6b6b6b; }
        .body { margin: 0 0 1rem; white-space: pre-wrap; }
        .files { margin: 0 0 1rem; color: #6b6b6b; font-size: 0.9rem; }
        .foot { margin-top: 1.5rem; color: #6b6b6b; font-size: 0.8rem; text-align: center; }
        @media print {
            body { padding: 0; background: #fff; }
            .sheet { max-width: none; border: 0; border-radius: 0; padding: 0; }
        }
    </style>
</head>
<body>
    <div class="sheet">
        <h1>Printable Ticket Version</h1>

        <div class="meta">
            <p><em>Ticket ID:</em> <span class="v">#{{ $ticket->id }}</span></p>
            <p><em>Department:</em> <span class="v">{{ $ticket->department ?: '—' }}</span></p>
            <p><em>Subject:</em> <span class="v">{{ $ticket->subject }}</span></p>
            <p><em>Creation Date:</em> <span class="v">{{ $ticket->created_at?->format('m/d/Y H:i') }}</span></p>
            <p><em>Owner:</em> <span class="v">{{ $ownerName }}</span></p>
            <p><em>Requestor:</em> <span class="v">{{ $requestorName }}@if ($requestorIsStaff)<span class="badge">Operator</span>@endif</span></p>
            <p><em>Last Reply:</em> <span class="v">{{ $lastReply?->created_at?->format('m/d/Y H:i') ?? '—' }}</span></p>
            <p><em>Status:</em> <span class="v">{{ $ticket->status }}</span></p>
            <p><em>Priority:</em> <span class="v">{{ $ticket->priority ?: '—' }}</span></p>
        </div>

        @foreach ($messages as $message)
            <hr>
            <p class="msg-head">
                {{ trim(($message->user->first_name ?? '') . ' ' . ($message->user->last_name ?? '')) ?: ($message->user->email ?? 'Unknown') }}
                @if ($message->user?->role_id)<span class="badge">Operator</span>@endif
                <span class="when">{{ $message->created_at?->format('m/d/Y H:i') }}</span>
            </p>
            <div class="body">{{ $message->message }}</div>
            @if ($message->attachments->isNotEmpty())
                <p class="files">
                    Attachments:
                    @foreach ($message->attachments as $attachment)
                        {{ $attachment->filename }}@if (!$loop->last), @endif
                    @endforeach
                </p>
            @endif
        @endforeach

        <hr>
        <p class="foot">Output Generated by {{ config('app.name', 'Paymenter') }}</p>
    </div>
</body>
</html>
